### ISSUE TITLE
Architecture : line 7: FIRMWARE_DIR: unbound variable

### ISSUE THREAD

**Issue by ZanderChang** [attify/firmware-analysis-toolkit#19]
I used DIR850LB1_FW210WWb03.bin to test but only get this result, how can I fix it ?
[+] Architecture : line 7: FIRMWARE_DIR: unbound variable
Traceback (most recent call last):
  File "fat.py", line 122, in <module>
    main()
  File "fat.py", line 114, in main
    arch = identify_arch(image_id)        
  File "fat.py", line 62, in identify_arch
    child.expect("Password for user firmadyne: ")    
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0xb71b16ec>
command: /home/zander/firmadyne/scripts/getArch.sh
args: ['/home/zander/firmadyne/scripts/getArch.sh', './images/1.tar.gz']
buffer (last 100 chars): ''

after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 2750
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('Password for user firmadyne: ')

**Comment by ZanderChang** [comment]
Oh sorry, I just forgot to remove the # before FIRMWARE_DIR in firmadyne.config.
