### ISSUE TITLE
Unable to execute the execute extractor.py

### ISSUE THREAD

**Issue by Minyanaing** [attify/firmware-analysis-toolkit#23]
When I run the fat.py, the program start and then I put the firmware and the brand. Then the error occurred as described below.
"""
Traceback (most recent call last):
File "fat.py", line 122, in
main()
File "fat.py", line 109, in main
image_id = run_extractor(firm_name, firm_brand)
File "fat.py", line 47, in run_extractor
child = pexpect.spawn(extractor_cmd, timeout=None)
File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 204, in init
self._spawn(command, args, preexec_fn, dimensions)
File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 276, in _spawn
'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: /home/firmadyne/sources/extractor/extractor.py.
"""

**Comment by extremecoders-re** [comment]
From the error message, looks like firmadyne (on which fat is based) isn't setup properly. It's failing on the line.
```
child = pexpect.spawn(extractor_cmd, timeout=None)
```
